const express = require("express");
const router = express.Router();
const customersRoute = require("./customer.route");
const rolesRoute = require("./role.route");
const usersRoute = require("./user.route");
const addressRoute = require("./address.route");
const userRoleRoute = require("./users-roles.route");
const contactsRoute = require("./contact.route");
const logsRoute = require("./log.route");
const authRoute = require("./auth.route");
router.use("/auth", authRoute);
router.use("/customers", customersRoute);
router.use("/roles", rolesRoute);
router.use("/users", usersRoute);
router.use("/address", addressRoute);
router.use("/users-roles", userRoleRoute);
router.use("/contacts", contactsRoute);
router.use("/logs", logsRoute);
module.exports = router;
